name: CI

on:
  push:
    branches: [main, feature/**]
  pull_request:
    branches: [main]

jobs:
  test:
    runs_on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Setup node.js 
        uses: actions/setup-node@v4 
        with: 
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install 
      
      - name: Run Tests
        run: npm test
        env:
          JWT_SECRET: test_secret_for_ci
          NODE_ENV: test